//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cosmaticstore029
{
    using System;
    using System.Collections.Generic;
    
    public partial class addproduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public addproduct()
        {
            this.orderdetails = new HashSet<orderdetail>();
            this.tltemporaries = new HashSet<tltemporary>();
        }
    
        public long productid { get; set; }
        public int typeid { get; set; }
        public int brandid { get; set; }
        public double productweight { get; set; }
        public string productcolor { get; set; }
        public string productname { get; set; }
        public int price { get; set; }
        public string productimage { get; set; }
    
        public virtual productbrand productbrand { get; set; }
        public virtual producttype producttype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderdetail> orderdetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tltemporary> tltemporaries { get; set; }
    }
}
