//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cosmaticstore029
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public int orderID { get; set; }
        public int OrdermainID { get; set; }
        public long Productid { get; set; }
        public int price { get; set; }
    
        public virtual addproduct addproduct { get; set; }
        public virtual tblmainOrder tblmainOrder { get; set; }
    }
}
